### ISSUE TITLE
An error in the size of the constraints

### ISSUE THREAD

**Issue by oroojlooy** [clvoloshin/constrained_batch_policy_learning#1]
Hi, 
Is this the final running version of the code? 
I tried to run the  code in `python 2`, and it seems that some of the required packages are no longer supported in `python 3`. So, I modified all the print statements and the code starts the training; though, it fails at `replay_buffer.py:58:`
`self.rewards[exp_idx] = reward`
with 
`ValueError: cannot copy sequence with size 7 to array axis with dimension 4`,

since the size of the `reward` is 7, and the `self.rewards` size is 4. The reward value comes from the `step` function of the car racing environment which is called in `run.py:243`, and after getting sum over the three frames, is passed into the `problem.collect` to be saved inside the `replay_buffer`. The value of the reward is tuple `(c,g)` and comes from the `step` function in `car_racing.py:297`, in which the values of the constraint, `g`, apparently has 6 elements:

`g = [step_fuel, step_acc, distance_to_track, self.car.hull.linearVelocity[0], self.car.hull.linearVelocity[1], action[2]>0]`,

which along with `c` is involves `7` elements and is returned to `reward`.  
On the other hand, in `config_car.py:38`, initial value for the constraint only includes 3 elements: `constraints = [5.8, 85.] + [0]` and `self.rewards[exp_idx]` is initialized to include `len(constraint)+1` elements. 

So, it seems that either the constraint in the config file needs a modification or the constraint environment. Since, in the paper there are two constraints, probably the environment needs the modification. If so, would you mind let me know if this is right? and If I modify `car_racing.py` accordingly, does not hurt the other parts of the code? 

Thanks,
Afshin

**Comment by clvoloshin** [comment]
If you’re trying to collect car data from scratch, there is a line that is missing which selects which g we care about.

Namely, line 216 of run.py: problem.dataset.data['g'] = problem.dataset.data['g'][:,constraints_cared_about]
Has to be copied over to line 279, so that g is the right length

**Comment by oroojlooy** [comment]
Thanks for the response. I copied `problem.dataset.data['g'] = problem.dataset.data['g'][:,constraints_cared_about]` at line 279, right after `problem.finish_collection(env_name)`. But this does not solve the issue and I still get the same error, since the error arises at line 265, i.e. `problem.collect` which is before the execution of line 279. 

Basically, `problem.collect` wants to fill the `replay_buffer` in which `self.rewards` is initialized to include `len(constraint)+1` elements. I can increase the size of the `constraint` in `config_car.py: constraints = [5.8, 85.] + [0]` to a list with 6 elements (like `constraints = [5.8, 85.] + [0] + [0, 0, 0]`), it solves the issue and starts to run the env and get some data. But, there is an issue, `[5.8, 85.]` are the limit for constraint 1 and 2:
`# Constraint 1: We'd like the number of times you brake to be less than 10% of the time `
`# Constraint 2: We'd like the car to stay within 15 units of the center of the track 90% of the time `
although, in the constraints vector 
`g = [step_fuel, step_acc, distance_to_track, self.car.hull.linearVelocity[0], self.car.hull.linearVelocity[1], action[2]>0]`
constraint 1 and 2 are not the first two elements and it seems that using `problem.dataset.data['g'] = problem.dataset.data['g'][:,constraints_cared_about]` removes wrong values from the obtained dataset. If this is correct, I think there should be another fix to this issue. Is this correct?

**Comment by clvoloshin** [comment]
in config_car, constraints_cared_about = [-1,2], which puts the values in the correct order. Probably the better way, is to actually replace line 263:   g = cost[1:].tolist()
with : g = cost[1:][constraints_cared_about].tolist()

**Comment by oroojlooy** [comment]
Thanks !
This solved the issue. However, I am getting a weird error on Keras, which I pasted it below. Do you have any idea? Beside, may I know which version of Keras, tensorflow, and numpy are you using?

```
  File "run.py", line 319, in main
    pi_t, values = problem.best_response(lambda_t, desc='FQI pi_{0}_{1}'.format(iteration, i), exact=exact_policy_algorithm)
  File "/net/ge.unx.sas.com/vol/vol110/u11/aforoo/constrained_batch_policy_learning/optimization_problem.py", line 53, in best_response
    policy = self.best_response_algorithm.run(self.dataset, **kw)
  File "/net/ge.unx.sas.com/vol/vol110/u11/aforoo/constrained_batch_policy_learning/fittedq.py", line 141, in run
    additional_callbacks = self.more_callbacks)
  File "/net/ge.unx.sas.com/vol/vol110/u11/aforoo/constrained_batch_policy_learning/fitted_algo.py", line 34, in fit_generator
    self.Q_k.fit_generator(generator, **kw)
  File "/net/ge.unx.sas.com/vol/vol110/u11/aforoo/constrained_batch_policy_learning/env_nn.py", line 325, in fit_generator
    self.model.fit_generator(generator,verbose=verbose==2, epochs=epochs, callbacks=self.callbacks_list, **kw)
  File "/usr/lib64/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/lib64/python3.6/site-packages/keras/engine/training_generator.py", line 185, in fit_generator
    generator_output = next(output_generator)
  File "/usr/lib64/python3.6/site-packages/keras/utils/data_utils.py", line 742, in get
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib64/python3.6/site-packages/keras/utils/data_utils.py", line 711, in get
    inputs = future.get(timeout=30)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/site-packages/keras/utils/data_utils.py", line 650, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
TypeError: 'ThreadSafe' object is not an iterator

```

**Comment by clvoloshin** [comment]
You probably have to modify the class ThreadSafe in thread_safe.py to make it a python3 object if you're using python3.

I no longer have access to the computer I used to run these experiments -- and so I can't say for certain what versions I had, sorry.

**Comment by clvoloshin** [comment]
Also, If you get things to run, I would appreciate if you could make a pull request so that I can merge the changes into this codebase so others can benefit too!

**Comment by oroojlooy** [comment]
> Also, If you get things to run, I would appreciate if you could make a pull request so that I can merge the changes into this codebase so others can benefit too!

Sure. I'll let you if I could make it work.
